# DEBUG_LEVEL: 0 - NO DEBUG | 1 -'EXCEPTION' | 2 -'ERROR' | 3 -'WARNING' | 4 -'INFO' and 'SUCCESS'
DEBUG_LEVEL = 0

# Supported algorithms
ALGORITHMS = ["MP", "CL"]

TCP_SOCKET_BUFFER_SIZE = 8 * 1024 * 1024
TCP_SOCKET_SERVER_LISTEN = 10
