# Global request states
REQUEST_SUBSCRIBE = 1
RESPONSE_SUBSCRIBE = 2
REQUEST_INFORMATION = 3
RESPONSE_INFORMATION = 4
EXCHANGE_MODEL = 5

REQUEST_EXCHANGE = 333
REQUEST_HELLO = 444
REQUEST_MODEL = 555
# Global response states
RESPONSE_EXCHANGE = 100
RESPONSE_HELLO = 101
RESPONSE_MODEL = 102



MESSAGE_TYPE_FETCH_PARAMETERS = 2

# // Global error states
NO_ERROR = 0
NO_MODEL = 1

# Callback events
NODE_INBOUND_CLOSED = 1
NODE_OUTBOUND_CLOSED = 2
CONNECTED_WITH_NODE = 3
NODE_CONNECTED = 4
NODE_MESSAGE = 5

# def callback_event(event, node, peer, data):

# Message types
