# Global request states
REQUEST_SUBSCRIBE = 10
RESPONSE_SUBSCRIBE = 11
REQUEST_INFORMATION = 12
RESPONSE_INFORMATION = 13
EXCHANGE_MODEL = 14
EXCHANGE_SOL_MODEL = 15
EXCHANGE_VARIABLES = 16
BANNED_NODE = 17

REQUEST_EXCHANGE = 333
REQUEST_HELLO = 444
REQUEST_MODEL = 555
REQUEST_STOP = 404
# Global response states
RESPONSE_EXCHANGE = 100
RESPONSE_HELLO = 101
RESPONSE_MODEL = 102

MESSAGE_TYPE_FETCH_PARAMETERS = 2

# // Global error states
NO_ERROR = 403
NO_MODEL = 404

# Callback events
NODE_INBOUND_CLOSED = 1
NODE_OUTBOUND_CLOSED = 2
CONNECTED_WITH_NODE = 3
NODE_CONNECTED = 4
NODE_MESSAGE = 5

# def callback_event(event, node, peer, data):
